-- MySQL Script generated by MySQL Workbench
-- Tue May 15 15:30:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema relationships_m2m
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `relationships_m2m` ;

-- -----------------------------------------------------
-- Schema relationships_m2m
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `relationships_m2m` DEFAULT CHARACTER SET utf8 ;
USE `relationships_m2m` ;

-- -----------------------------------------------------
-- Table `relationships_m2m`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `relationships_m2m`.`products` ;

CREATE TABLE IF NOT EXISTS `relationships_m2m`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `price` DECIMAL(9) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `relationships_m2m`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `relationships_m2m`.`categories` ;

CREATE TABLE IF NOT EXISTS `relationships_m2m`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `relationships_m2m`.`categories_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `relationships_m2m`.`categories_products` ;

CREATE TABLE IF NOT EXISTS `relationships_m2m`.`categories_products` (
  `product_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `category_id`),
  INDEX `fk_products_has_categories_categories1_idx` (`category_id` ASC),
  INDEX `fk_products_has_categories_products_idx` (`product_id` ASC),
  CONSTRAINT `fk_products_has_categories_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `relationships_m2m`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_categories_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `relationships_m2m`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
